name: openai-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - openai==1.108.2
    - langchain-core==0.3.78
    - langchain-openai==0.3.35
    - langgraph==0.6.8
    - pydantic==2.11.9
    - pydantic-settings==2.10.1
    - boto3
    - requests==2.32.5
    - python-dotenv==1.1.1
    - typing-extensions==4.15.0
    - PyMuPDF==1.26.4
    - numpy==2.3.3
    - PyYAML==6.0.3
